# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QhhY+VvWEQGpov+GFeDQiTw+Hp/ecSp/iQDxHcuGaY3/y827Y9se5Vi05SIwnmfFDkMCrarGb7w0rqlRzmITBW02N0iKrmljjQAHBKGG7FM2Y2IL6lzPfSqU4z1ZYT018UYuwZnHQd4Lmjzw2RTJvL1dtPXuBThiceSY4l/TzdJHNEO5cBZSYFl44nPTvLNsBCq71H9dJlTKMoWpQ3vXusPva3o+nMnGksc1yqEzSgkdbDdToX5IizjSQE+c5ujE09sYAFw+67BG10A6PUq0zHAcdEzNU4Nu/mMQABvgSDZ6eqwlT7HrZjFwq8geqnuIWVzp+9T/DNNsKIGPH2N60KCg7Ff0fgzWgyFySyeRBnLXnmez4U2bQ80Mlba5QEufmSQILyb9eXfwIPTBH8VS1S9ExgHziuSM5fQnEqoDbj+w0yU32R9jAXVmYwamCihdl4xBT8yzdRb/E6Wq1Wr9Qu7uBkmn91cKzYRSdR1tmXJnyV/JEl9eSjoEM8gfXwsfgkWImDiQo5SGabhLH9CRyYOTxwzIMe3fFDTzmdK0LbRPr+qobBUXNooF/m3njM4GvktdD2leSyOiFju7BxaLaHb2l6AavinsDbe3tKX3voszmldi/FWiI+dScUATfa51Sztd36dsvgVnGinoDVC+032aM+ZDVRUgm60X7RYZGYE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
