# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nYGHREa/87ipzYGMrfC9xGVigGltdMHgNiklpRfEWvj9VrnB8qUeBmiZaR+SntGpfjfxrAVQWO/VExBwzu5x8TCE3/klSyFzVh1sKj6sYsfbQl2qoWkOA5KWY7aCHNEHjcE9VUKgdcXK3Vom0JnJTKWlxj/RWzRfeatGJNqdtnMzYDBH2mEp3zXmkrY7XAWJrUCD2qtUYs2Se68O7zRMPb/4wxs5Il3mfH12QdJVF2dPRkP15uvVFtYgGJE0viq8wAgJmccV2HW+JFvW0oZyr81hlowNcTJFZsjtPN2CjFdVBS1wsBporJwmYjVakjUpm4jWzrENyxfR2/RWM3up2szdxLGCy49YJNpnO7VuHWMHtB9smgE3olnpI5B8StwjrOh+eWRgBXBa1UK3e8+s3wOthW6V2GmG9zU2rZ4LuRRbKE7OgcVEDuSt09BCkiFsPv2YtBTszYYHKKP5xQmQF5uyjDOiaHUcLn8u4elhZG5//GOgBveLU9ewtHX3/T3cmzGEPTmgOz9yh5hszhi0xOcWzEwfDdM3Lq8sV6cE+hQ3+LPqEsosiQKwaJKVjN2Pz/YHy1ABz9mrN9I00k6xQRnaUjOPgGquvEnE3hLSdwPxo+xpdjCdQmEsmDmeAQwZ2gMFL1cS656/RErOk7PhfpxbmWETTxYagLv8Rh9Bi7I="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
