travis:
  secure:
    BINSTAR_TOKEN: QhhY+VvWEQGpov+GFeDQiTw+Hp/ecSp/iQDxHcuGaY3/y827Y9se5Vi05SIwnmfFDkMCrarGb7w0rqlRzmITBW02N0iKrmljjQAHBKGG7FM2Y2IL6lzPfSqU4z1ZYT018UYuwZnHQd4Lmjzw2RTJvL1dtPXuBThiceSY4l/TzdJHNEO5cBZSYFl44nPTvLNsBCq71H9dJlTKMoWpQ3vXusPva3o+nMnGksc1yqEzSgkdbDdToX5IizjSQE+c5ujE09sYAFw+67BG10A6PUq0zHAcdEzNU4Nu/mMQABvgSDZ6eqwlT7HrZjFwq8geqnuIWVzp+9T/DNNsKIGPH2N60KCg7Ff0fgzWgyFySyeRBnLXnmez4U2bQ80Mlba5QEufmSQILyb9eXfwIPTBH8VS1S9ExgHziuSM5fQnEqoDbj+w0yU32R9jAXVmYwamCihdl4xBT8yzdRb/E6Wq1Wr9Qu7uBkmn91cKzYRSdR1tmXJnyV/JEl9eSjoEM8gfXwsfgkWImDiQo5SGabhLH9CRyYOTxwzIMe3fFDTzmdK0LbRPr+qobBUXNooF/m3njM4GvktdD2leSyOiFju7BxaLaHb2l6AavinsDbe3tKX3voszmldi/FWiI+dScUATfa51Sztd36dsvgVnGinoDVC+032aM+ZDVRUgm60X7RYZGYE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
