travis:
  secure:
    BINSTAR_TOKEN: Sf+tw1A/JuqdLHAhE0pIleKA3y480lHTdAKsN1Gc/6T/n6Bq0ieMEyyu03XAF4qaOQxt7Ihb04/G+go8yjihvLAZ8IJINzbX4Z5KeYCt3EsanCGZ3Mao+4CMDK65GuF3EtaWn5wedlO8kQe30mqTQGVhzPojpITOz7lb7pGywLNaIcZ/vPyKFNNGhxaXS+dku0AZmAuzpswsBS6r8tMpNaNTPKNy5dlgQF4lpyQnLt67Rz7zHSyTj7W2yUSLLeIwlf0zrPPEhNYa2ODeZl5u73XmGyxfiGBZ+75nMHVG1SJO/dBoRuT1Q5e5pkPKOruesZ4TikdqPfZiS0ZtbFGc71VHHm++OeYkEo5utNzEjnQifoLpYnaMNPHIk6pMD+yWX8b+iZny98Zu9WzsUURTK1PFT/KdNZGqnPu7HQhsHVlWTrSF8kBiNoyxuiAo6LzhsEtYNzO+S/96tU7jUMlAxT2BtdSzC00nAKlBTPCywoJqAjxI1poIhUOlJnyP2Py77SRHol7oR+EX0sSBKXhDZ+6Z04xc3qx8kF8v/QvAyf2g3TW9BRDScHMif1x0xNTFAN2NORq+c3uYEkwsOitXLqkdZdByoRUCZDWrsImxFfeq3mUPNQ/+BR0U50PxCBkfR5HgMbmDzjN0dJtrlPxX53tVyxiCIY/6ABYxvSVvOMY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
